name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - pyyaml
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - pip:
      - mlflow==3.3.2
      - wandb==0.22.0
